version: '3'

services:
  flask-app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data  
    depends_on:
      - redis

  redis:
    image: redis:7
    ports:
      - "6379:6379"
