version: '3.8'

services:
  flask-app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - REDIS_IP=redis
    depends_on:
      - redis
    volumes:
      - ./src:/app/src

  redis:
    image: redis:7
    ports:
      - "6379:6379"
