version: '3'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data
    command: ["--save", "1", "1"]

  worker:
        build:
            context: ./
            dockerfile: Dockerfile
        image: nicoleolv/fqhcs-app:1.0
        depends_on:
            - redis-db
        command: ["python3", "worker.py"]

